apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: geth-status-influxdb
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: geth-status-influxdb
  template:
    metadata:
      labels:
        k8s-app: geth-status-influxdb
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      containers:
      - name: geth-status-influxdb
        image: kuberstack/geth-status-influxdb
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi